namespace Proyecto_Tienda.Services;

public class MonedaRepositorioEnMemoria : IMonedaRepositorio
{
    private readonly List<Moneda> _monedas;

    public MonedaRepositorioEnMemoria()
    {
        _monedas = new List<Moneda>
        {
            new Moneda { Id = 1, Nombre = "Dólar Estadounidense", Codigo = "USD", Simbolo = "$" },
            new Moneda { Id = 2, Nombre = "Euro", Codigo = "EUR", Simbolo = "€" },
            new Moneda { Id = 3, Nombre = "Libra Esterlina", Codigo = "GBP", Simbolo = "£" },
            new Moneda { Id = 4, Nombre = "Yen Japonés", Codigo = "JPY", Simbolo = "¥" },
            new Moneda { Id = 5, Nombre = "Peso Mexicano", Codigo = "MXN", Simbolo = "$" },
            new Moneda { Id = 6, Nombre = "Franco Suizo", Codigo = "CHF", Simbolo = "CHF" },
            new Moneda { Id = 7, Nombre = "Dólar Canadiense", Codigo = "CAD", Simbolo = "$" },
            new Moneda { Id = 8, Nombre = "Dólar Australiano", Codigo = "AUD", Simbolo = "$" },
            new Moneda { Id = 9, Nombre = "Yuan Chino", Codigo = "CNY", Simbolo = "元" },
            new Moneda { Id = 10, Nombre = "Real Brasileño", Codigo = "BRL", Simbolo = "R$" },
            new Moneda { Id = 11, Nombre = "Rupia India", Codigo = "INR", Simbolo = "₹" },
            new Moneda { Id = 12, Nombre = "Rublo Ruso", Codigo = "RUB", Simbolo = "₽" },
            new Moneda { Id = 13, Nombre = "Won Surcoreano", Codigo = "KRW", Simbolo = "₩" },
            new Moneda { Id = 14, Nombre = "Dólar de Singapur", Codigo = "SGD", Simbolo = "$" },
            new Moneda { Id = 15, Nombre = "Dólar Neozelandés", Codigo = "NZD", Simbolo = "$" },
            new Moneda { Id = 16, Nombre = "Peso Argentino", Codigo = "ARS", Simbolo = "$" },
            new Moneda { Id = 17, Nombre = "Lira Turca", Codigo = "TRY", Simbolo = "₺" },
            new Moneda { Id = 18, Nombre = "Rand Sudafricano", Codigo = "ZAR", Simbolo = "R" },
            new Moneda { Id = 19, Nombre = "Peso Chileno", Codigo = "CLP", Simbolo = "$" },
            new Moneda { Id = 20, Nombre = "Dirham de los Emiratos Árabes Unidos", Codigo = "AED", Simbolo = "د.إ" },
            new Moneda { Id = 21, Nombre = "Corona Sueca", Codigo = "SEK", Simbolo = "kr" },
            new Moneda { Id = 22, Nombre = "Dólar Hongkonés", Codigo = "HKD", Simbolo = "$" },
            new Moneda { Id = 23, Nombre = "Corona Noruega", Codigo = "NOK", Simbolo = "kr" },
            new Moneda { Id = 24, Nombre = "Ringgit Malayo", Codigo = "MYR", Simbolo = "RM" },
            new Moneda { Id = 25, Nombre = "Peso Colombiano", Codigo = "COP", Simbolo = "$" },
            new Moneda { Id = 26, Nombre = "Forinto Húngaro", Codigo = "HUF", Simbolo = "Ft" },
            new Moneda { Id = 27, Nombre = "Corona Danesa", Codigo = "DKK", Simbolo = "kr" },
            new Moneda { Id = 28, Nombre = "Baht Tailandés", Codigo = "THB", Simbolo = "฿" },
            new Moneda { Id = 29, Nombre = "Zloty Polaco", Codigo = "PLN", Simbolo = "zł" },
            new Moneda { Id = 30, Nombre = "Nuevo Sol Peruano", Codigo = "PEN", Simbolo = "S/" },
            new Moneda { Id = 31, Nombre = "Shekel Israelí", Codigo = "ILS", Simbolo = "₪" },
            new Moneda { Id = 32, Nombre = "Dinar Kuwaití", Codigo = "KWD", Simbolo = "د.ك" },
            new Moneda { Id = 33, Nombre = "Dólar Taiwanés", Codigo = "TWD", Simbolo = "$" },
            new Moneda { Id = 34, Nombre = "Peso Filipino", Codigo = "PHP", Simbolo = "₱" },
            new Moneda { Id = 35, Nombre = "Dinar Saudí", Codigo = "SAR", Simbolo = "ر.س" },
            new Moneda { Id = 36, Nombre = "Rupia Indonesia", Codigo = "IDR", Simbolo = "Rp" },
            new Moneda { Id = 37, Nombre = "Lira Siria", Codigo = "SYP", Simbolo = "£" },
            new Moneda { Id = 38, Nombre = "Leu Rumano", Codigo = "RON", Simbolo = "lei" },
            new Moneda { Id = 39, Nombre = "Dinar Iraquí", Codigo = "IQD", Simbolo = "ع.د" },
            new Moneda { Id = 40, Nombre = "Som Uzbeko", Codigo = "UZS", Simbolo = "сум" },
            new Moneda { Id = 41, Nombre = "Dólar Jamaicano", Codigo = "JMD", Simbolo = "$" },
            new Moneda { Id = 42, Nombre = "Dólar Fiyiano", Codigo = "FJD", Simbolo = "$" },
            new Moneda { Id = 43, Nombre = "Leu Moldavo", Codigo = "MDL", Simbolo = "L" },
            new Moneda { Id = 44, Nombre = "Dólar de Belice", Codigo = "BZD", Simbolo = "$" },
            new Moneda { Id = 45, Nombre = "Libra Egipcia", Codigo = "EGP", Simbolo = "£" },
            new Moneda { Id = 46, Nombre = "Dólar de Barbados", Codigo = "BBD", Simbolo = "$" },
            new Moneda { Id = 47, Nombre = "Dólar de Guyana", Codigo = "GYD", Simbolo = "$" },
            new Moneda { Id = 48, Nombre = "Dólar de las Bahamas", Codigo = "BSD", Simbolo = "$" },
            new Moneda { Id = 49, Nombre = "Córdoba Nicaragüense", Codigo = "NIO", Simbolo = "C$" },
            new Moneda { Id = 50, Nombre = "Boliviano", Codigo = "BOB", Simbolo = "Bs." },
            new Moneda { Id = 51, Nombre = "Dólar de Trinidad y Tobago", Codigo = "TTD", Simbolo = "$" },
            new Moneda { Id = 52, Nombre = "Guaraní Paraguayo", Codigo = "PYG", Simbolo = "₲" },
            new Moneda { Id = 53, Nombre = "Dólar Namibio", Codigo = "NAD", Simbolo = "$" },
            new Moneda { Id = 54, Nombre = "Dólar de Zimbabue", Codigo = "ZWL", Simbolo = "$" },
            new Moneda { Id = 55, Nombre = "Dólar de Surinam", Codigo = "SRD", Simbolo = "$" },
            new Moneda { Id = 56, Nombre = "Rupia Maldiva", Codigo = "MVR", Simbolo = "ރ." },
            new Moneda { Id = 57, Nombre = "Franco CFA", Codigo = "XAF", Simbolo = "Fr" },
            new Moneda { Id = 58, Nombre = "Franco Burundés", Codigo = "BIF", Simbolo = "Fr" },
            new Moneda { Id = 59, Nombre = "Franco Ruandés", Codigo = "RWF", Simbolo = "Fr" },
            new Moneda { Id = 60, Nombre = "Chelín Tanzano", Codigo = "TZS", Simbolo = "Sh" },
            new Moneda { Id = 61, Nombre = "Franco de Guinea", Codigo = "GNF", Simbolo = "Fr" },
            new Moneda { Id = 62, Nombre = "Chelín Ugandés", Codigo = "UGX", Simbolo = "Sh" },
            new Moneda { Id = 63, Nombre = "Franco de Comoras", Codigo = "KMF", Simbolo = "Fr" },
            new Moneda { Id = 64, Nombre = "Franco de Djibouti", Codigo = "DJF", Simbolo = "Fr" },
            new Moneda { Id = 65, Nombre = "Dólar de Liberia", Codigo = "LRD", Simbolo = "$" },
            new Moneda { Id = 66, Nombre = "Franco Congoleño", Codigo = "CDF", Simbolo = "Fr" },
            new Moneda { Id = 67, Nombre = "Escudo Caboverdiano", Codigo = "CVE", Simbolo = "$" },
            new Moneda { Id = 68, Nombre = "Franco Malgache", Codigo = "MGA", Simbolo = "Ar" },
            new Moneda { Id = 69, Nombre = "Franco CFP", Codigo = "XPF", Simbolo = "Fr" },
            new Moneda { Id = 70, Nombre = "Rial Iraní", Codigo = "IRR", Simbolo = "﷼" },
            new Moneda { Id = 71, Nombre = "Rial Omaní", Codigo = "OMR", Simbolo = "﷼" },
            new Moneda { Id = 72, Nombre = "Rupia de Seychelles", Codigo = "SCR", Simbolo = "₨" },
            new Moneda { Id = 73, Nombre = "Dólar de Brunei", Codigo = "BND", Simbolo = "$" },
            new Moneda { Id = 74, Nombre = "Rupia de Mauricio", Codigo = "MUR", Simbolo = "₨" },
            new Moneda { Id = 75, Nombre = "Rial Catarí", Codigo = "QAR", Simbolo = "ر.ق" },
            new Moneda { Id = 76, Nombre = "Dólar de las Islas Salomón", Codigo = "SBD", Simbolo = "$" },
            new Moneda { Id = 77, Nombre = "Rupia de Pakistán", Codigo = "PKR", Simbolo = "₨" },
            new Moneda { Id = 78, Nombre = "Rial Yemení", Codigo = "YER", Simbolo = "﷼" },
            new Moneda { Id = 79, Nombre = "Franco de Burundi", Codigo = "BIF", Simbolo = "Fr" },
            new Moneda { Id = 80, Nombre = "Franco CFA BEAC", Codigo = "XAF", Simbolo = "Fr" },
            new Moneda { Id = 81, Nombre = "Rial Camboyano", Codigo = "KHR", Simbolo = "៛" },
            new Moneda { Id = 82, Nombre = "Ngultrum Butanés", Codigo = "BTN", Simbolo = "Nu." },
            new Moneda { Id = 83, Nombre = "Rupia de Sri Lanka", Codigo = "LKR", Simbolo = "₨" },
            new Moneda { Id = 84, Nombre = "Manat Azerbaiyano", Codigo = "AZN", Simbolo = "₼" },
            new Moneda { Id = 85, Nombre = "Som Kirguís", Codigo = "KGS", Simbolo = "с" },
            new Moneda { Id = 86, Nombre = "Tenge Kazajo", Codigo = "KZT", Simbolo = "₸" },
            new Moneda { Id = 87, Nombre = "Tugrik Mongol", Codigo = "MNT", Simbolo = "₮" },
            new Moneda { Id = 88, Nombre = "Rupia Nepalí", Codigo = "NPR", Simbolo = "₨" },
            new Moneda { Id = 89, Nombre = "Somoni Tayiko", Codigo = "TJS", Simbolo = "ЅМ" },
            new Moneda { Id = 90, Nombre = "Dram Armenio", Codigo = "AMD", Simbolo = "֏" },
            new Moneda { Id = 91, Nombre = "Rupia Butanesa", Codigo = "INR", Simbolo = "₹" },
            new Moneda { Id = 92, Nombre = "Kina Papua Nueva Guinea", Codigo = "PGK", Simbolo = "K" },
            new Moneda { Id = 93, Nombre = "Rupia Malaya", Codigo = "MAL", Simbolo = "M$" },
            new Moneda { Id = 94, Nombre = "Balboa Panameño", Codigo = "PAB", Simbolo = "B/." },
            new Moneda { Id = 95, Nombre = "Colón Costarricense", Codigo = "CRC", Simbolo = "₡" },
            new Moneda { Id = 96, Nombre = "Lilangeni Suazi", Codigo = "SZL", Simbolo = "L" },
            new Moneda { Id = 97, Nombre = "Dólar de Namibia", Codigo = "NAD", Simbolo = "$" },
            new Moneda { Id = 98, Nombre = "Pula de Botsuana", Codigo = "BWP", Simbolo = "P" },
            new Moneda { Id = 99, Nombre = "Dalasi Gambiano", Codigo = "GMD", Simbolo = "D" },
            new Moneda { Id = 100, Nombre = "Leone de Sierra Leona", Codigo = "SLL", Simbolo = "Le" },
            new Moneda { Id = 101, Nombre = "Quetzal Guatemalteco", Codigo = "GTQ", Simbolo = "Q" },
            new Moneda { Id = 102, Nombre = "Dólar de Kiribati", Codigo = "KID", Simbolo = "$" },
            new Moneda { Id = 103, Nombre = "Dólar de Tuvalu", Codigo = "TVD", Simbolo = "$" },
            new Moneda { Id = 104, Nombre = "Franco de Burundi", Codigo = "BIF", Simbolo = "Fr" },
            new Moneda { Id = 105, Nombre = "Som Uzbeko", Codigo = "UZS", Simbolo = "сум" },
            new Moneda { Id = 106, Nombre = "Tala Samoano", Codigo = "WST", Simbolo = "T" },
            new Moneda { Id = 107, Nombre = "Franco de Djibouti", Codigo = "DJF", Simbolo = "Fr" },
            new Moneda { Id = 108, Nombre = "Rial de Yemen", Codigo = "YER", Simbolo = "﷼" },
            new Moneda { Id = 109, Nombre = "Franco de Guinea", Codigo = "GNF", Simbolo = "Fr" },
            new Moneda { Id = 110, Nombre = "Dólar de Belice", Codigo = "BZD", Simbolo = "$" },
            new Moneda { Id = 111, Nombre = "Dólar de las Islas Cook", Codigo = "CKD", Simbolo = "$" },
            new Moneda { Id = 112, Nombre = "Dólar de Fiyi", Codigo = "FJD", Simbolo = "$" },
            new Moneda { Id = 113, Nombre = "Dólar de Niue", Codigo = "NUD", Simbolo = "$" },
            new Moneda { Id = 114, Nombre = "Dólar de Palaos", Codigo = "PLW", Simbolo = "$" },
            new Moneda { Id = 115, Nombre = "Rupia Seychelles", Codigo = "SCR", Simbolo = "₨" },
            new Moneda { Id = 116, Nombre = "Rupia de las Maldivas", Codigo = "MVR", Simbolo = "ރ." },
            new Moneda { Id = 117, Nombre = "Peso Uruguayo", Codigo = "UYU", Simbolo = "$" },
            new Moneda { Id = 118, Nombre = "Rupia de Bangladesh", Codigo = "BDT", Simbolo = "৳" },
            new Moneda { Id = 119, Nombre = "Peso Cubano", Codigo = "CUP", Simbolo = "$" },
            new Moneda { Id = 120, Nombre = "Peso Dominicano", Codigo = "DOP", Simbolo = "$" },
            new Moneda { Id = 121, Nombre = "Escudo Ecuatoguineano", Codigo = "GQE", Simbolo = "₵" },
            new Moneda { Id = 122, Nombre = "Florín de Aruba", Codigo = "AWG", Simbolo = "ƒ" },
            new Moneda { Id = 123, Nombre = "Metical Mozambicano", Codigo = "MZN", Simbolo = "MT" },
            new Moneda { Id = 124, Nombre = "Dólar de Singapur", Codigo = "SGD", Simbolo = "$" },
            new Moneda { Id = 125, Nombre = "Rupia Nepalí", Codigo = "NPR", Simbolo = "₨" },
            new Moneda { Id = 126, Nombre = "Peso Convertible Cubano", Codigo = "CUC", Simbolo = "$" },
            new Moneda { Id = 127, Nombre = "Dólar de Barbados", Codigo = "BBD", Simbolo = "$" },
            new Moneda { Id = 128, Nombre = "Shilling Somalí", Codigo = "SOS", Simbolo = "Sh" },
            new Moneda { Id = 129, Nombre = "Peso Boliviano", Codigo = "BOB", Simbolo = "Bs." },
            new Moneda { Id = 130, Nombre = "Colon Salvadoreño", Codigo = "SVC", Simbolo = "$" },
            new Moneda { Id = 131, Nombre = "Lempira Hondureño", Codigo = "HNL", Simbolo = "L" },
            new Moneda { Id = 132, Nombre = "Naira Nigeriano", Codigo = "NGN", Simbolo = "₦" },
            new Moneda { Id = 133, Nombre = "Escudo Portugués", Codigo = "PTE", Simbolo = "₱" },
            new Moneda { Id = 134, Nombre = "Rupia Ceilanesa", Codigo = "LKR", Simbolo = "₨" },
            new Moneda { Id = 135, Nombre = "Rupia Seychelense", Codigo = "SCR", Simbolo = "₨" },
            new Moneda { Id = 136, Nombre = "Franco CFA de Camerún", Codigo = "XAF", Simbolo = "Fr" },
            new Moneda { Id = 137, Nombre = "Rupia Paquistaní", Codigo = "PKR", Simbolo = "₨" },
            new Moneda { Id = 138, Nombre = "Chelín Keniano", Codigo = "KES", Simbolo = "Sh" },
            new Moneda { Id = 139, Nombre = "Dólar de Jamaica", Codigo = "JMD", Simbolo = "$" },
            new Moneda { Id = 140, Nombre = "Pataca Macanesa", Codigo = "MOP", Simbolo = "P" },
            new Moneda { Id = 141, Nombre = "Ngultrum Butanés", Codigo = "BTN", Simbolo = "Nu." },
            new Moneda { Id = 142, Nombre = "Rupia de Sri Lanka", Codigo = "LKR", Simbolo = "₨" },
            new Moneda { Id = 143, Nombre = "Franco Burundés", Codigo = "BIF", Simbolo = "Fr" },
            new Moneda { Id = 144, Nombre = "Dólar de Bahamas", Codigo = "BSD", Simbolo = "$" },
            new Moneda { Id = 145, Nombre = "Taka de Bangladesh", Codigo = "BDT", Simbolo = "৳" },
            new Moneda { Id = 146, Nombre = "Rupia India", Codigo = "INR", Simbolo = "₹" },
            new Moneda { Id = 147, Nombre = "Dólar de Nueva Zelanda", Codigo = "NZD", Simbolo = "$" },
            new Moneda { Id = 148, Nombre = "Dólar de Hong Kong", Codigo = "HKD", Simbolo = "$" },
            new Moneda { Id = 149, Nombre = "Franco Congoleño", Codigo = "CDF", Simbolo = "Fr" },
            new Moneda { Id = 150, Nombre = "Dólar de Guyana", Codigo = "GYD", Simbolo = "$" },
            new Moneda { Id = 151, Nombre = "Dólar de Zimbabwe", Codigo = "ZWL", Simbolo = "$" },
            new Moneda { Id = 152, Nombre = "Franco Suizo", Codigo = "CHF", Simbolo = "CHF" },
            new Moneda { Id = 153, Nombre = "Libra Esterlina", Codigo = "GBP", Simbolo = "£" },
            new Moneda { Id = 154, Nombre = "Rublo Soviético", Codigo = "SUR", Simbolo = "₽" },
            new Moneda { Id = 155, Nombre = "Dinar Libio", Codigo = "LYD", Simbolo = "ل.د" },
            new Moneda { Id = 156, Nombre = "Peso Ecuatoriano", Codigo = "ECS", Simbolo = "S/" },
            new Moneda { Id = 157, Nombre = "Rupia Srilankesa", Codigo = "LKR", Simbolo = "₨" },
            new Moneda { Id = 158, Nombre = "Bolívar Venezolano", Codigo = "VES", Simbolo = "Bs." },
            new Moneda { Id = 159, Nombre = "Quetzal Guatemalteco", Codigo = "GTQ", Simbolo = "Q" },
            new Moneda { Id = 160, Nombre = "Peso Dominicano", Codigo = "DOP", Simbolo = "$" },
            new Moneda { Id = 161, Nombre = "Dólar de Timor Oriental", Codigo = "USD", Simbolo = "$" },
            new Moneda { Id = 162, Nombre = "Franco CFA de África Central", Codigo = "XAF", Simbolo = "Fr" },
            new Moneda { Id = 163, Nombre = "Pula de Botsuana", Codigo = "BWP", Simbolo = "P" },
            new Moneda { Id = 164, Nombre = "Dólar de las Islas Marianas", Codigo = "USD", Simbolo = "$" },
            new Moneda { Id = 165, Nombre = "Dólar Australiano", Codigo = "AUD", Simbolo = "$" },
            new Moneda { Id = 166, Nombre = "Peso Uruguayo", Codigo = "UYU", Simbolo = "$" },
            new Moneda { Id = 167, Nombre = "Franco CFA", Codigo = "XOF", Simbolo = "Fr" },
            new Moneda { Id = 168, Nombre = "Franco Centroafricano", Codigo = "XAF", Simbolo = "Fr" },
            new Moneda { Id = 169, Nombre = "Dólar Namibio", Codigo = "NAD", Simbolo = "$" },
            new Moneda { Id = 170, Nombre = "Chelín Somalí", Codigo = "SOS", Simbolo = "Sh" },
            new Moneda { Id = 171, Nombre = "Florín de Aruba", Codigo = "AWG", Simbolo = "ƒ" },
            new Moneda { Id = 172, Nombre = "Dólar de Hong Kong", Codigo = "HKD", Simbolo = "$" },
            new Moneda { Id = 173, Nombre = "Rupia Paquistaní", Codigo = "PKR", Simbolo = "₨" },
            new Moneda { Id = 174, Nombre = "Manat Azerbaiyano", Codigo = "AZN", Simbolo = "₼" },
            new Moneda { Id = 175, Nombre = "Dólar de Brunei", Codigo = "BND", Simbolo = "$" },
            new Moneda { Id = 176, Nombre = "Rupia India", Codigo = "INR", Simbolo = "₹" },
            new Moneda { Id = 177, Nombre = "Franco de Madagascar", Codigo = "MGA", Simbolo = "Ar" },
            new Moneda { Id = 178, Nombre = "Kwacha Malauí", Codigo = "MWK", Simbolo = "MK" },
            new Moneda { Id = 179, Nombre = "Dírham Marroquí", Codigo = "MAD", Simbolo = "د.م." },
            new Moneda { Id = 180, Nombre = "Rupia de las Maldivas", Codigo = "MVR", Simbolo = "ރ." }
        };
    }

    public IEnumerable<Moneda> ObtenerTodas()
    {
        return _monedas;
    }

    public Moneda ObtenerPorId(int id)
    {
        // Buscar la moneda por su Id
        // Mediante LINQ 
        // LINQ significa Language Integrated Query (Consulta Integrada de Lenguaje)
        return _monedas.FirstOrDefault(m => m.Id == id);
    }
}
